cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

main/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
     path('',views.index, name='home'),
     path('contact/', views.contact, name="contact"),
     path('register/', views.register, name="register"),
     path('login/', views.login, name='login'),
     #path("logout/", views.logout, name="logout"),
     path('comments/', views.crudindex, name='comment'),
     path('comments/upload/', views.crud_upload, name='crud_upload'),
     path('comments/update/<int:crud_id>', views.crud_update),
     path('comments/delete/<int:crud_id>', views.crud_delete),
     #####################################################################
     path('product_list/', views.product_list, name='product_list'),
     path('<slug:category_slug>/', views.product_list,
          name='product_list_by_category'
          ),
     path('<int:id>/<slug:slug>', views.product_detail, 
          name='product_detail'),
     #####################################################################
     
     
]

pet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('', RedirectView.as_view(url='main/')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('django.contrib.auth.urls')),
    
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title></title>
</head>
<body style="background: white">
<header class="header" style="background: white">
        <div class="container">
            <nav>
                <a href="{% url 'main:home' %}"><img src="{% static 'images/old_logo.png' %}" class="logo" style="height: 70px; width: 70px;"></a>
                <ul class="nav-links" style="color: black">
                    <li><a href="{% url 'main:home' %}" style="color: black">Home</a></li>
                    <li><a href="{% url 'main:product_list' %}" style="color: black">Pets</a></li>
                    <li><a href="{% url 'main:contact' %}" style="color: black">Contacts</a></li>
                    <li>
                        <div class="cart">
                            {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                            Cart:
                            <a href="{% url 'cart:cart_detail' %}" style="color: black">
                                {{ total_items }} штук ,${{ cart.get_total_price }}
                            </a>
                            {% else %}
                            Cart empty
                            {% endif %}
                            {% endwith %}
                        </div>
                    </li>
                    <li><a href="{% url 'main:register' %}" class="btn-header">{{ User.name }} Accaunt</a></li>
                </ul>
            </nav>
        </div>
    </header>
{% load static %}
<link rel="stylesheet" href="{% static 'css/product_details.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
{% block title %}
{% endblock %}
<table class="cart">
    <section class="h-100" >
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">
          <div class="d-flex justify-content-between align-items-center mb-4">
          <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
          <div>
            <p class="mb-0"><span class="text-muted">Sort by:</span> <a href="#!" class="text-body">price <i
                  class="fas fa-angle-down mt-1"></i></a></p>
          </div>
        </div>
      {% for item in cart %}
        {% with product=item.product %}
          <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}
                    {% static 'img/no_image.png' %}{% endif %}" style="height: 200px; width: 150px;">
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <p class="lead fw-normal mb-2">{{ product.name }}</p>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="Обновить">
                    {% csrf_token %}
                </form>
              </div>

              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0">${{ item.price }}</h5>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2">
                    <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
              </div>
            </div>
          </div>
        </div>

        {% endwith %}
        {% endfor %}
        <div class="card"><div class="card-body">
            <button type="button" class="btn btn-warning btn-block btn-lg">Proceed to Pay</button>
          </div>
      </div>
      </div>
    </div>
  </div>
</section>

</table>
<div class="footer-basic">

<footer>
           <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
           <ul class="list-inline">
               <li class="list-inline-item"><a class="fff" href="#">Home</a></li>
               <li class="list-inline-item"><a class="fff" href="#">Services</a></li>
               <li class="list-inline-item"><a class="fff" href="#">About</a></li>
               <li class="list-inline-item"><a class="fff" href="#">Terms</a></li>
               <li class="list-inline-item"><a class="fff" href="#">Privacy Policy</a></li>
           </ul>
           <p class="copyright">Zoo © <script>document.write(new Date().getFullYear());</script></p>
       </footer>
     </div>
</body>

</html>