cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

main/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
     path('',views.index, name='home'),
     path('contact/', views.contact, name="contact"),
     path('register/', views.register, name="register"),
     path('login/', views.login, name='login'),
     #path("logout/", views.logout, name="logout"),
     path('comments/', views.crudindex, name='comment'),
     path('comments/upload/', views.crud_upload, name='crud_upload'),
     path('comments/update/<int:crud_id>', views.crud_update),
     path('comments/delete/<int:crud_id>', views.crud_delete),
     #####################################################################
     path('product_list/', views.product_list, name='product_list'),
     path('<slug:category_slug>/', views.product_list,
          name='product_list_by_category'
          ),
     path('<int:id>/<slug:slug>', views.product_detail, 
          name='product_detail'),
     #####################################################################
     
     
]

pet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('', RedirectView.as_view(url='main/')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('django.contrib.auth.urls')),
    
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse
from tabnanny import verbose

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image = models.ImageField(upload_to='main/static/images', blank=True)
    description = models.TextField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)
    howtocare = models.CharField(
        max_length=300, db_index=True, default='Это монстр, уход не нужен, он тебе поможет')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail', args=[self.id, self.slug])


class Comment(models.Model):
    comment = models.TextField(max_length=200)
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class User(models.Model):
    username = models.CharField(max_length = 50)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=50)


    def __str__(self):
        return self.username

    
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

class CRUD(models.Model):
    animal_name = models.CharField(max_length = 50)
    email = models.EmailField(blank=True)
    comment = models.TextField(default = 'Здесь крч хорошая птица и неплохой бэкенд')
    def __str__(self):
        return self.animal_name


class PetInstance(models.Model):
    ...
    class Meta:
        ...
        permissions = (("can_mark_returned", "Set pet as returned"),)

main/forms.py
from .models import User, Comment
from django.forms import ModelForm, TextInput
from django import forms
from .models import CRUD



class CRUDCreate(forms.ModelForm):
    class Meta:
        model = CRUD
        fields = '__all__'


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "password"]
        widgets = {
            "username": TextInput(attrs={
                'class': 'form__input',
                'placeholder': 'Username'
            }),
            "email": TextInput(attrs={
                'class': 'form__input',
                'placeholder': 'Email'
            }),
            "password": TextInput(attrs={
                'class': 'form__input',
                'placeholder': 'Пароль'
            }),
        }


class UserComment(ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        #fields = ["comment", "email"]
        widgets = {
            "comment": TextInput(attrs={
                'class': 'form-otzyv',
                'placeholder': 'Напишите что думаете о нашем магазине'
            }),
            "email": TextInput(attrs={
                'class': 'form-otzyv',
                'placeholder': 'Email'
            }),
        }

main/views.py
from django.shortcuts import render, HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.contrib.auth import authenticate
from cart.forms import CartAddProductForm
from unicodedata import name
from django.shortcuts import render, redirect
from .models import User, CRUD
from .forms import UserComment, UserForm, CRUDCreate
from django.shortcuts import get_object_or_404
from .models import Category, Product
# Create your views here.



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'main/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'main/detail.html', {'product': product, 'cart_product_form': cart_product_form})


def index(request):
    return render(request, 'main/index.html')


def contact(request):
    print(request.POST)
    error = ''
    if request.method == 'POST':
        form = UserComment(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
            #redirect('home')    --- после логина на хоум, а пока не надо
        else:
            error = 'Форма была невеноой'

    form = UserComment()
    context = {
        'form': form,
        'error': error
    }
    return render(request, 'main/contacts.html', context)


def register(request):
    print(request.POST, "REGISTER")
    error = ''
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            #redirect('home')    --- после логина на хоум, а пока не надо
        else:
            error = 'Форма была невеноой'

    form = UserForm()
    context = {
        'form': form,
        'error': error
    }
    return render(request, 'main/register.html')


def login(request):
    print(request.POST)
    if request.user.is_authenticated:
        return redirect("/")
    else:
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                alert = True
                return render(request, "main/register.html", {"alert": alert})
    return render(request, "main/register.html")

#def logout(request):


















#CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---CRUD---


def crudindex(request):
    shelf = CRUD.objects.all()
    return render(request, 'main/comments.html', {'shelf': shelf})


def crud_upload(request):
    upload = CRUDCreate()
    if request.method == 'POST':
        upload = CRUDCreate(request.POST, request.FILES)
        if upload.is_valid():
            upload.save()
            return redirect('main:comment')
        else:
            return HttpResponse("""your form is wrong, reload on <a href = "{{ url : 'main:comment'}}">reload</a>""")


    else:
        return render(request, 'main/upload_form.html', {'upload_form': upload})


def crud_update(request, crud_id):
    crud_id = int(crud_id)
    try:
        crud_sel = CRUD.objects.get(id=crud_id)
    except CRUD.DoesNotExist:
        return redirect('main:comment')
    crud_form = CRUDCreate(request.POST or None, instance=crud_sel)
    if crud_form.is_valid():
       crud_form.save()
       return redirect('main:comment')
    return render(request, 'main/upload_form.html', {'upload_form': crud_form})


def crud_delete(request, crud_id):
    crud_id = int(crud_id)
    try:
        crud_sel = CRUD.objects.get(id=crud_id)
    except CRUD.DoesNotExist:
        return redirect('main:comment')
    crud_sel.delete()
    return redirect('main:comment')

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title></title>
</head>
<body style="background: linear-gradient(0deg, grey ,black, #d3d3d3)">
<header class="header" style="background: white">
            <nav>
                <a href="{% url 'main:home' %}"><img src="{% static 'images/old_logo.png' %}" class="logo" style="height: 70px; width: 70px; float: left"></a>
                <ul class="nav-links" style="color: black">
                    <li><a href="{% url 'main:home' %}" style="color: black">Home</a></li>
                    <li><a href="{% url 'main:product_list' %}" style="color: black">Pets</a></li>
                    <li><a href="{% url 'main:contact' %}" style="color: black">Contacts</a></li>
                    <li>
                        <div class="cart">
                            {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                            Cart:
                            <a href="{% url 'cart:cart_detail' %}" style="color: black">
                                {{ total_items }} штук ,${{ cart.get_total_price }}
                            </a>
                            {% else %}
                            Cart empty
                            {% endif %}
                            {% endwith %}
                        </div>
                    </li>
                    <li><a href="{% url 'main:register' %}" class="btn-header">{{ User.name }} Accaunt</a></li>
                </ul>
            </nav>
    </header>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

main/templates/main/contacts.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/contacts.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>Contacts</title>
</head>
<div class="container">
<header class="header" style="background: white">
            <a href="{% url 'main:home' %}"><img src="{% static 'images/old_logo.png' %}" class="logo" style="float: left; height: 70px; width: 70px;"></a>
            <ul class="nav-links" style="color: black" >
                <li style="float: right"><a href="{% url 'main:register' %}" class="btn-header">{{ User.name }} Accaunt</a></li>
                <li style="float: right">
                        <div class="cart">
                            {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                            Cart:
                            <a href="{% url 'cart:cart_detail' %}" style="color: black">
                                {{ total_items }} штук ,${{ cart.get_total_price }}
                            </a>
                            {% else %}
                            Cart empty
                            {% endif %}
                            {% endwith %}
                        </div>
                    </li>
                <li style="float: right"><a href="{% url 'main:contact' %}" style="color: black">Contacts</a></li>
                <li style="float: right"><a href="{% url 'main:product_list' %}" style="color: black">Pets</a></li>
                <li style="float: right"><a href="{% url 'main:home' %}" style="color: black">Home</a></li>
                </ul>
    </header>
</div>
<body class="159">
	<section class="ftco-section">
			<div class="row justify-content-center">
				<div class="col-md-12">
					<div class="wrapper">
						<div class="row no-gutters mb-5">
							<div class="col-md-7">
								<div class="contact-wrap w-100 p-md-5 p-4">
									<h3 class="mb-4">Contact Us</h3>
									<div id="form-message-warning" class="mb-4"></div>
                                    <div id="form-message-success" class="mb-4">
                                        Your message was sent, thank you!
                                    </div>
                                    <form action="" class="form-otzyv" method="POST">
                                        <h3 class="form__title">Your feedback</h3>
                                        {% csrf_token %}
                                        <!--   чтобы форма работало  - csrf_token нужен-->
                                        <p>
                                            <input type="text" class="form__input" placeholder="Share opinion about our website"
                                                   name="comment">
                                        </p>
                                        <p>
                                            <input type="email" class="form__input" placeholder="Email" name="email">
                                        </p>
                                        <p>
                                            <button type="submit" value="Submit" class="form__btn">submit</button>
                                        </p>

                                        <span>{{error}}</span>
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-2 mt-2 d-flex align-items-stretch">
                                <div class="map">
                                    <iframe
                                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2505.9543933324935!2d71.41613421563008!3d51.09084917956886!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x424585a605525605%3A0x4dff4a1973f7567e!2sAstana%20IT%20University!5e0!3m2!1sru!2skz!4v1648180682329!5m2!1sru!2skz"
                                            width="600" height="500" style="border:1px solid rgb(224, 170, 22); border-radius: 10px;" allowfullscreen="" loading="lazy"
                                            referrerpolicy="no-referrer-when-downgrade">
                                    </iframe>
                                </div>
							</div>
						</div>
					</div>
				</div>
			</div>
	</section>
<div></div>
	<script src="js/jquery.min.js"></script>
  <script src="js/popper.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.validate.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="js/google-map.js"></script>
  <script src="js/main.js"></script>
<div>
    <br>
    <br>
    <br>
</div>
<div class="footer-basic">

  <footer>
             <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
             <ul class="list-inline">
                 <li class="list-inline-item"><a class="fff" href="#">Home</a></li>
                 <li class="list-inline-item"><a class="fff" href="#">Services</a></li>
                 <li class="list-inline-item"><a class="fff" href="#">About</a></li>
                 <li class="list-inline-item"><a class="fff" href="#">Terms</a></li>
                 <li class="list-inline-item"><a class="fff" href="#">Privacy Policy</a></li>
             </ul>
             <p class="copyright">Zoo © <script>document.write(new Date().getFullYear());</script></p>
         </footer>
       </div>
	</body>


</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Pet shop</title>
</head>

<body>
<div class="container">
<header class="header" style="background: white">
            <a href="{% url 'main:home' %}"><img src="{% static 'images/old_logo.png' %}" class="logo" style="float: left; width: 70px; height: 70px"></a>
            <ul class="nav-links" style="color: black" >
                <li style="float: right"><a href="{% url 'main:register' %}" class="btn-header">{{ User.name }} Account</a></li>
                <li style="float: right">
                        <div class="cart">
                            {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                            Cart:
                            <a href="{% url 'cart:cart_detail' %}" style="color: black">
                                {{ total_items }} штук ,${{ cart.get_total_price }}
                            </a>
                            {% else %}
                            Cart empty
                            {% endif %}
                            {% endwith %}
                        </div>
                    </li>
                <li style="float: right"><a href="{% url 'main:contact' %}" style="color: black">Contacts</a></li>
                <li style="float: right"><a href="{% url 'main:product_list' %}" style="color: black">Pets</a></li>
                <li style="float: right"><a href="{% url 'main:home' %}" style="color: black">Home</a></li>
                </ul>
    </header>
</div>
<div class="container-fluid bg-2 text-align: center ">
<div class="row">

  <div class="col-sm-4">

    <div class="coupon">
     <div class="container1">
       <h1>Free!</h1>
     </div>
     <img src="{% static 'images/fish1.png' %}" alt="Avatar" style="width:100%;">
     <div class="container1" >
       <a type="button"  href="{% url 'main:product_list' %}"><h1>Buy 1 Get Respect</h1> </a>
       <p>Buy and get respect</p>
     </div>
     <div class="container1">
       <p class="expire">Expires: June 03, 2022</p>
     </div>
   </div>
  </div>
  <div>
    <div class="col-sm-4">

      <div class="coupon">
       <div class="container1">
         <h1>Free!</h1>
       </div>
       <img src="{% static 'images/cat1.png' %}" alt="Avatar" style="width:90%;">
       <div class="container1" >
         <a type="button"  href="{% url 'main:product_list' %}"><h1>Buy and get free delivery</h1> </a>
         <p>Buy and get free delivery</p>
       </div>
       <div class="container1">
         <p class="expire">Expires: June 03, 2022</p>
       </div>
     </div>
   </div>
     <div class="col-sm-4">

       <div class="coupon">
        <div class="container1">
          <h1>Free!</h1>
        </div>
        <img src="{% static 'images/bird2.png' %}" alt="Avatar" style="width:80%;">
        <div class="container1" >
          <a type="button"  href="{% url 'main:product_list' %}"><h1>Buy 1 Get 2</h1> </a>
          <p>Only here you can buy 1 but get 2</p>
        </div>
        <div class="container1">
          <p class="expire">Expires: June 03, 2022</p>
        </div>
      </div>
    </div>

</div>
</div>
</div>
<div class="container-fluid bg-3 text-center">
  <h1 class="margin">Pets</h1><br>
  <div class="row">
    <div class="col-sm-4">
      <img class="image" src="{% static 'images/cat1.png' %}" class="img-responsive margin" style="width:100%" alt="Image">
      <p>Animals (lat. Animalia) is a traditionally (since the time of Aristotle) ​​distinguished category of organisms, currently considered as a biological kingdom. Animals are the main object of study of zoology.
    </div>
    <div class="col-sm-4">
      <img class="image" src="{% static 'images/fish1.png' %}" class="img-responsive margin" style="width:100%" alt="Image">
        <p>Fish (lat. Pisces) is a paraphyletic group (according to the modern cladistic classification) of aquatic vertebrates. An extensive group of jawed mouths, which are characterized by gill breathing at all stages of the postembryonic development of the organism. </p>    </div>
    <div class="col-sm-4">
      <img class="image" src="{% static 'images/bird3.png' %}" class="img-responsive margin" style="width:100%" align="center" alt="Image">
      <p>Birds (lat. Aves) are a group of warm-blooded egg-laying vertebrates, traditionally considered as a separate class. Well isolated from other groups of modern animals.</p>
    </div>
  </div>
</div>


    <div class="jumbotron">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="item active">
            <img src="{% static 'images/pes1.png' %}" alt="">
            <div class="carousel-caption">
            </div>
          </div>
          <div class="item">
            <img src="{% static 'images/husky-section1.png' %}" alt="">
            <div class="carousel-caption">
            </div>
          </div>
          <div class="item">
            <img src="{% static 'images/pes3.png' %}" alt="">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>


<div class="container-fluid bg-2 text-center">
  <h1 class="margin">Who we are</h1>

  <div class="row">
          <div class="row">
          <div class="col-xs-8 col-sm-6">
          <img src="{% static 'images/pes2.png' %}" alt="">
          </div>
              <div class="col-xs-4 col-sm-6">
              <h1>We are the best pet store. our animals undergo all medical examinations, they have vaccination passports. We have created all conditions for animals. You can be sure that your new friend is absolutely healthy and clean.</h1>
          </div>
          </div>
  </div>

</div>




<div class="footer-basic">

<footer>
           <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
           <ul class="list-inline">
               <li class="list-inline-item"><a class="fff" href="{% url 'main:home' %}" style="color: black">Home</a></li>
               <li class="list-inline-item"><a class="fff" href="{% url 'main:product_list' %}" style="color: black">Pets</a></li>
               <li class="list-inline-item"><a class="fff" href="{% url 'main:contact' %}" style="color: black">Contacts</li>
           </ul>
           <p class="copyright">Zoo © <script>document.write(new Date().getFullYear());</script></p>
       </footer>
     </div>
</body>

</html>

main/templates/main/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/register.css' %}" type="text/css">
    <script src="{% static 'js/register.js' %}" defer></script>

    <title>ACCOUNT</title>
</head>
<header class="header" style="background: white">
        <div class="container">
            <nav>
                <a href="{% url 'main:home' %}"><img src="{% static 'images/old_logo.png' %}" class="logo" style="height: 100px; width: 100px; float: left"></a>
                <ul class="nav-links" style="color: black">
                    <li><a href="{% url 'main:home' %}" style="color: black">Home</a></li>
                    <li><a href="{% url 'main:product_list' %}" style="color: black">Pets</a></li>
                    <li><a href="{% url 'main:contact' %}" style="color: black">Contacts</a></li>
                    <li>
                        <div class="cart">
                            {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                            В корзине:
                            <a href="{% url 'cart:cart_detail' %}" style="color: black">
                                {{ total_items }} штук ,${{ cart.get_total_price }}
                            </a>
                            {% else %}
                            Корзинка пустая
                            {% endif %}
                            {% endwith %}
                        </div>
                    </li>
                    <li><a href="{% url 'main:register' %}" class="btn-header">{{ User.name }} Accaunt</a></li>
                </ul>
            </nav>
        </div>
    </header>

<body>
    <div class="register_body">
        <article class="container-register">
            <div class="block">
                <section class="block__item block-item">
                    <h2 class="block-item__title">У вас уже есть аакуант?</h2>
                    <button class="block-item__btn signin-btn">Войти</button>
                </section>
                <section class="block__item block-item">
                    <h2 class="block-item__title">У вас нет аккаунта?</h2>
                    <button class="block-item__btn signup-btn">Зарегистрироваться</button>
                </section>
            </div>


            <div class="form-box">
                <form class="form form_signin" method="POST" action="{% url 'main:login' %}">
                    <h3 class="form__title">Вход</h3>
                    {% csrf_token %}
                    <p>
                        <input type="text" class="form__input" placeholder="Логин" name="username">
                    </p>
                    <p>
                        <input type="password" class="form__input" placeholder="Пароль" name="password">
                    </p>
                    <p>
                        <button type="submit" value="Submit" class="form__btn">Войти</button>
                    </p>
                    <p>
                        <a href="#" class="form__forgot">Восстановить пароль</a>
                    </p>
                </form>
                <!--  Другая форма ---------------------------------------------------------------------------------------------------------------------->
                <form class="form form_signup" method="POST">
                    <h3 class="form__title">Регистрация</h3>
                    {% csrf_token %}
                    <!--   чтобы форма работало  - csrf_token нужен-->

                    <p>
                        <input type="text" class="form__input" placeholder="Username" name="username">
                    </p>
                    <p>
                        <input type="email" class="form__input" placeholder="Email" name="email">
                    </p>
                    <p>
                        <input type="password" class="form__input" placeholder="Пароль" name="password">
                    </p>
                    <p>
                        <input type="password" class="form__input" placeholder="Повторите пароль" name="password2">
                    </p>
                    <p>
                        <button type="submit" value="Submit"
                            class="form__btn form__btn__signup">Зарегистрироваться</button>
                    </p>
                    <span>{{error}}</span>
                </form>
            </div>
        </article>
    </div>
</body>
<style>
    body {
    background-image: linear-gradient(to left, black ,grey, white);
    margin: 0;
    padding: 0;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;

    min-height: 100vh;

    transition: 0.5s;
}


body.active {
     background-image: linear-gradient(to right, black, grey , white);
}
</style>
</html>